[target.'cfg(all(target_arch = "arm", target_os = "none"))']


linker = "flip-link"
rustflags = [
  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tlink.x",

  # Code-size optimizations.
  #   trap unreachable can save a lot of space, but requires nightly compiler.
  #   uncomment the next line if you wish to enable it
  # "-Z", "trap-unreachable=no",
  "-C", "no-vectorize-loops",
]

# runner, cargo run builds uf2 for this target
runner = "elf2uf2-rs -d"

[build]
target = "thumbv6m-none-eabi"